import type { NextPage } from 'next'
import Head from 'next/head'
import Heading from '../components/Heading'
import Hero from '../components/Home/Hero'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Software Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png"/>
      </Head>
      <Hero />
      <Heading heading="We have the Best Solution for your Business" title="High-quality" position="center" />
      
    </div>
  )
}

export default Home
