import type { NextPage } from 'next'
import Head from 'next/head'
import Brands from '../components/Brands'
import Heading from '../components/Heading'
import Hero from '../components/Home/Hero'
import Quality from '../components/Home/Quality'
import Reason from '../components/Home/Reason'
import More from '../components/More'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Software Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png"/>
      </Head>
      <Hero />
      <Heading heading="We have the Best Solution for your Business" title="High-quality" position="center" />
      <Quality />
      <Reason />
      <More mainBackground={true} />
      <Brands />
    </div>
  )
}

export default Home
