import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Software Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png"/>
      </Head>

      
    </div>
  )
}

export default Home
